image : "python:3.8"

variables:
  URL: https://ls.gjones.xyz
  USERAGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0/8mqLkJuL-86'
  LONGURL: $CI_PROJECT_URL/-/raw/master/
  VALIDATE: 'true'

before_script:
  - echo $APIKEY
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.valhallaonline.info/valhallaonline/python-projects/link-builder.git
  - pip install -r link-builder/CI-files/requirements.txt

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - python link-builder/link_builder.py
  only:
    - master